version: '3.8'

services:
  nginx:
    container_name: cotrang_nginx
    image: nginx:1.23.2-alpine
    ports:
      - "9797:80"
    volumes:
      - .:/app
      - /app/vendor
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - network

  app:
    container_name: cotrang_app 
    build:
      context: ./.
      dockerfile: ./docker/php/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - network

  database:
    container_name: database
    image: library/mysql:8.0
    ports:
      - 3309:3306 
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: cotrang
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: cotrang
    volumes:
      - data:/var/lib/mysql
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - network

  phpmyadmin:
    container_name: cotrang_phpmyadmin
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - network

  composer:
    container_name: composer
    image: composer:latest
    networks:
      - network
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: sh -c "composer clearcache && composer update && php artisan key:generate && composer dump-autoload"

volumes:
  data:
    driver: local

networks:
  network:
    driver: bridge
